services:
  - type: web
    name: business-card-ocr
    runtime: python
    rootDir: 3_app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: TESSDATA_PREFIX
        value: "/usr/share/tesseract-ocr/4.00/tessdata"
      - key: PYTHONUNBUFFERED
        value: "1"